[package]
name = "cannoli_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mempipe = { path = "../mempipe" }
libc = "*"

[build-dependencies]
bindgen = "*"

[lib]
crate-type = ["cdylib"]

