[package]
name = "example_visualization"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
snuffles = { git = "https://github.com/gamozolabs/snuffles" }
cannoli = { path = "../cannoli" }

